version: '3.4'

services:
  auctionsdb:
    container_name: auctionsdb
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"

  bidmasteronline.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=auctionsdb;Database=AuctionsDb;User Id=sa;Password=SwN12345678;TrustServerCertificate=True;TrustServerCertificate=True"
      - "AllowedOrigins=http://localhost:4201"
    depends_on:
      - auctionsdb
    ports:
      - "8000:80"

  client:
    ports:
      - "4201:80"

